# Reduced limits for WAAM (smoother, safer motion)
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 1.0  # rad/s 
    has_acceleration_limits: true
    max_acceleration: 0.5  # rad/s²
    has_jerk_limits: false
    
  joint_2:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.5
    
  joint_3:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.5
    
  joint_4:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: true
    max_acceleration: 0.6
    
  joint_5:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: true
    max_acceleration: 0.6
    
  joint_6:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.8