# Reduced limits for WAAM (smoother, safer motion)
joint_limits:
  joint_a1:
    has_velocity_limits: true
    max_velocity: 1.0  # rad/s 
    has_acceleration_limits: true
    max_acceleration: 0.5  # rad/s²
    has_jerk_limits: false
    
  joint_a2:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.5
    
  joint_a3:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.5
    
  joint_a4:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: true
    max_acceleration: 0.6
    
  joint_a5:
    has_velocity_limits: true
    max_velocity: 1.2
    has_acceleration_limits: true
    max_acceleration: 0.6
    
  joint_a6:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: true
    max_acceleration: 0.8