
cartesian_limits:
  max_trans_vel: 0.5      # m/s - Maximum translational velocity
  max_trans_acc: 0.3      # m/s² - Maximum translational acceleration
  max_trans_dec: 0.3      # m/s² - Maximum translational deceleration
  max_rot_vel: 0.785      # rad/s - Maximum rotational velocity (45 deg/s)
  max_rot_acc: 0.5        # rad/s² - Maximum rotational acceleration
  max_rot_dec: 0.5        # rad/s² - Maximum rotational deceleration