; generated by PrusaSlicer 2.9.3 on 2025-10-23 at 11:58:23 UTC


;
; thumbnail begin 160x120 9876
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAActUlEQVR4Ae2dWbMURdrHzxd4Y2Zu3o
; s3dF4HHXB0hjFGL2aYoxwQFXAXREBBZHHfRUVFcAcBBVRQQFDEXUDcEEQ9GkqoIRdOGOHXqTm/HP89
; efJkVWVWVXdXNX3x6KG7upbMXz5PPktmDdx5553JrFmzkgsvvDC57rrrkoULFybTp0+vTK644opk3r
; x55vyXX355smzZMnO9qs5/ySWXJLfeemvy1ltvJVu2bDHn5nrXXHNNcvHFF5tjLrjgglw5//zzU4Xv
; ufelS5ea5+EzrrF48eJk5syZyXnnnZcq06ZNC5Jzzz3XCO20aNGiZMGCBcn27duTV199Nbn77rvNua
; ZOnZopU6ZMCRLOf9ddd5lr0UY8x0UXXZQMDQ21ZPLkyblyzjnneIV7mT9/vunrOXPmJLNnzzbPw7XP
; PvvsUTJgd9CMGTPMD2644QbTsXxWFAzOdeWVV5rz2J8LdBoh5nw+aIDg0UcfTT788MPklltuaX0OFF
; wbCHl49/dZsLnCc9CY3DN/23DxbNdff72Bk2OLQofwb9peCkCfrVixwgyup59+2lynKHhAxXmXL1+e
; XHvtteb8go2/r7766mTu3LlB8C2Z8ddU+OhfgFZ76XPah+vSN6MA9HUso4KGpYNDtIfv9wDADfi+F5
; yAfumll0afn4fg/l5++eXktddeSy677LIxx9DYfM4z0Lj8JhY+aQfAsAGzRQ3LCOf8MdBJuFcGJG3C
; OfnMBgwwdu7caTQibabvQ8FDOMd9991nBo39uYTP+A5weCYfeGtnn5T866YBI2tm/f8o8Pie+8dK0O
; Y+bcd1rrrqKiP8JhVAQULHoUbVeSGCCfQB4RPUPudHw8Sc//77708++uij5MEHH8zUanzOiJQ21H2l
; ASeoOAboZJpCzCummWfh+FDwEH6n67jg2cL1nnjiieSNN95IVq9ebfokBDzOyRQFcLkPFzwXMo5hQH
; Ff9ucAJ/gkexf+dkQbTmwNwiVLlhiIBZdP+I5753ieaSBr3oOgobh5Oj5PK2HuYmAV6IwYNBqwpB0n
; LbFx48Zk7969ZkSHajLN4bgOo49zpWk0NQ6Dwj0mT7txXjqBa0iTpQnnZlDoOqHzO86/Z8+e5Pnnnz
; e/TwMPoe/uvfde03ecI3SOx3n4De2wbs4fxoBny6uXDZh7wgLQBmngucI1UHADofMgbgbxaRA0Cx0c
; a+JsQBg5gA7E7vd8d/vttyfvvvtusn79+hZAoSJTiZZBs/Hg/G0Dxt88A41Jx8XO56TlNJdDq9FuPv
; gw7Zg6rsPxsY4FA3Xz5s3J7t27DWCuZhOotBnPFetcSDbMPTkVvMMLBpK10waSO/8+YLRlltbL0oYD
; MZAwKtBUACEwMW80SBHwfKAzCadzBDMa4vHHH0/ef/9906h5oOWJPHPOC+z2dINrh8zjQkwrmpT5EF
; DbcKK50RbcRxmPlmOIYLz55ptmUPJMAMZ1cTR4HlvrxYCHWcW8Zmk9wJPEgjfKCfFNqrOEBwQEBBMQ
; q41CQKcx8Wpvu+02E4bYsWNH5lysiKCF5N0yqICxLHQ+4RrAwPUAnEGcpvVCwyi2RqOtdu3aZWTVql
; XJAw88YBRCEfDQSL65XhZ8RQEcHBw0MhDbcQCijnPjYCGmMETQqo888kgyPDxstF/Mb0McBkThFSAH
; DJndssC5jgT/RuM99NBDLciLQOfzXCUogVdeeSU5dOhQ8tRTT5nBGgteHnw+8IoCKPiiAQQ25jd0nu
; ZUmBkatgqtBNyA/eKLLyYHDhww5orryRMvAppPOBcOjRwZtJPCAzLBZaCTcG7g5rxck2fjb85fFjoJ
; Jh6TywDimbAYBOSZr1cBXh58MQDa4LUApDFCOpYHtCfnNjSYYh6ev4vCx7yS6Py+ffvGaD1MChAK9J
; g5mi38FpMFCAqXaG7GoOL8aEX7u1joJDwPbQLc9rEKu6C1yoDHMUwdbr755pYTAlS0G3NC4qMEsflu
; ckYGIws+29EoA6APvFEAZonmZHRQFqx4wkBCw8fCxxxpzZo1Bj658777kOmPdRQUImGgIFzTB5QGGp
; pRc7VQ4GyTq+C3wisuXNw/ECqzEQqdhAGJ1kOb8nufdrvppptMzPCZZ54xA8sFL9bRyBL6hfPHwMd3
; WIVMANEENFKo1lGsjhsK+Q03cOONN7biWnlgSVMCukIYaWKnuPgNHc4gCTGndDCdBohKi4XApxiirp
; NnXgFIAy4UQEw6uWEUQp6TgfbdunWryaIw1+X4KkyuK/SbQnQhWo97oz9++OEHP4AyVXRErKbht3Qe
; c0M6JO04HI2HH344+eCDD4zHG3MNHpSOQMtkmUo0EJ2s6UGoSdVvAQkIgT0PQp5ZedwQ50JA0UbKhG
; RByP0AnvK4oc4FvyVz9PrrrydPPvlk8uz88ZWBZ5tgroPmpx2yAOQ5Nm3alHzzzTemfQfcYCn/jtF6
; WdoNCAHN/pwboMFfeukl0yg+TRaipTRIBLovDqf8auz8zQYRMDiH8sEuXHI09JxF5nWck6kBsPsyFp
; ybgDOaPE/rpRUJPL/o9Eq1nm8OyHVoL9qDtrPB4zuUwVdffWUA5N9mDogWUniADtWkuQqhc1S2pLTe
; PffcYzzclStXBsOWJWgczi/QBCbwAWEIaHmiLAmA0MCCUJ4nliJN64XO6xAVA/BMAhMng2nKNI8zEQ
; JemfBKqLhzO+6bqQUajuvTL/T3999/bz4f5YQw8SfQywhTQrxKoeHoKMwA5L/33ntmJFR9DUBnbggQ
; /B2q5UIDwtKGOCcMWMw/1wH4osD5UmQ8C2YWLUL1CtfivFWDVxV8LoC2xmPAMm0gi0XGhucc4wVjWg
; Dj4MGDLTVfJRxoIaoxBLom3bHnyQKG8zHaCEswn+QZygKXlv7iOuRYFcopA53PnPIZ50ZjML3AcsRA
; FwpfSHilDIA8B9r72LFjJsLB1M4bhpH5AIxPPvnExJCYj4RokDxogJuMBqVTaCeBQhqvSvPISFPYQ2
; GdtGeIyTy48PE8tJOqu/k32t2dt8VCJ8H0MkVRHpd/AyPTInmwIVJVeKUogNz3tm3bkiNHjpi24p40
; jx6TCbE7h84jiv72228bTQK1RaEAMgpGERc2ZTy4qTLwqbqaOZ87MABDoBeFzo7bYRK5DudWIJj2wS
; SrkLQIdBIGERaIZ/J9pyLPOpjcNAC5BwbP0aNHjcdtw8bfKjZBEXkBlAAf2hDtFQsJHc/chTJ5gqVZ
; ZpNz40DIuwwVfqt6tayMAuflGEZeDHB2tgFNxzloPJ+51RyXeS3w6Jg84CQATYwOc8vfaSZWa0Vkkj
; vtaOQBSDuQwQI+2iItDEP7qPyfQTVgmxhbUPtE0gli0jiM8Kk55hjzRMHoO++8M0YrpYmqazDNeaZS
; 2pPrAFWISeW+gFWgh3qpNChmnOvw91BOWkzBaz13CHw8M4OU/4eYWK7Ds/M87QoqFxHm3B9//LGxdj
; xXVhBaJnrt2rXJY4899l8A0zqcKg60IVqNke47DogYxRSMUjZOp8doHDqY7InmbWkg8aBoI2maGFG4
; Rp2dJTgXXCfPyXCdBwWv0ewMlDRNyOcMagXgQx0LCdfAlK2bM650HrcK+e6774wDmAceZhjFRuaLqp
; 2zzjorG0AJWgBXGm+ZEShIABR1i+qlTN5XIh4q0roq8bK/Q/uiroE0BO40YPitCkJ9jgO/5XmUSoyd
; xyGcA3DRhgxY93eYchwNrpM3p0uTxdMnJvsX/a6rWs8WBl4efLQD+emvv/7atD/wBQMoDURimzgeYR
; UVH1D+88ILL4yJhxUVzsPolunT3MfVvkVCHra5FOj6XI6G7dWGzuN8Gk7rUBTk5zMaHpOLNo7Veso2
; rJn1+66bXN8cMEsAlFw/ikrgtQC0OyZEmK8dPnzYrFX97LPPDIxVgGeDpRAOJecqwy8KXJY2ZDLMdZ
; i3aVllGfBcAWQGKhqVFXw8C58VAS8Pvm6AlwcgbYBVJMbMumYXvlEAhnYaJgyaf/zxx2T//v0m2JgX
; gojVUGgIgMDsov1C5m1FBOBIcwG6ytiLwpYGEBqQoLLWF4cA6JY01VHr5QGI1sfJYOMAH3jRANJBd9
; xxh8lokD+mITEnn376qVmHUAUkCuNo0Y4+U9lSbMA3Cyjmm4xOnktlZJjMssBJuDar/JTH1eo+HBSf
; CU4r5syCD0ejm+D5AOSesSg4pHI0SgGIRkLrkU5RHtf+nk4DSpWBF4EEkaOhybl7D5q32Qtu8iCbnO
; Ik8DyIneDnc5VU+cIoMWaTe8TR4Hzcnz7nPMw7CaMw0HReH3g4GnXWerYwqLTWF2vCclGmN3nw5QLI
; qMW9xm3esGFDKlxcmMg3njJa0gdJFuAcT8e7G+TYgPF/zds0CGLNJJqH66D9uG7aMapwifVO+T2DkD
; ag7dKOUwW5qq5j5npV53HLymPXz2xtoMTKvBCtNwrAtM5CjTJ3YZ5HzCoEJuCgwBRtqY1usjQVQDF6
; +J2yACEaTOst6OSQ33BtOpvr0PlZ2k3XQBvzDKHaTwWjCkVlmVaZaFXXCPY6Oxo+mTPp92YAER35+e
; efk2effTYKPi+AgEDnUjBKFkTzlVDh95SBk0VhDuSDRA6AasaKaDNAQtvkzduU0eA4ab1QbQYgAj3r
; WJwL5sM2SKE7A9AOtMHmBX9qjMld8o/ftBwNlA3ORix4o+KA6iwanFGMFqNBi4AhUT4Zh8WGhOvR4M
; AXqsEmZ2hD5lmae7rfoylVJh8KnitKMWr7CVu4PlEALIS82yKLtJ++8qRGaT2eE8tFYTEptaLwGQDp
; IEDAPDHPI48b4w1mCUATL6Q0hxgYIGhLjDJwT7ZMJ/9X2ZI0EDBgQkPDHiEerYoSOJ9SSjgaDCbuoQ
; h4dQ+vuDLjn38xz681JmXAawFIA7LdFzQTLKwCjMmOuaWqhtowRgtQhMIVI0oZYjIZVHKEysInraZ5
; HhCS9yYA73MgqoCvk3ncUK3HPaNQcDhwOKuAzwBIoJCCUdxnLYopAkDaPEpxPM6PSaZaBi1YFRz2tV
; TehUm0d+eMhS1N0LTU7AEfZplniAWP8Mrehb9plMnlOYmGsFUKg7sq+AyAxO80krWSrMycyQZCuyZg
; rqSl8JQw8ySm+b4K+FQFrd0/mbdxXTzMorC5zgImHZOrALm2rEMr9qLJBTx7GaUvj1sJgD5Txuh2g6
; gxIkdD4RX3e+aDaF1Mcx4keUJAF9hcT5UBwD3Y87Yiwm+1BoTnsr/j32hznqEMfHV1NHg26vzS8rht
; AVCizpN2jNFG3Li2eE07Du3Hjk4ELzGbsc4Cx6vz0+Juuh/t0RILH22A1svadpbP5W37QH/qiuZova
; WTfpssnv2fnVsJrZQJr5QGENESQRo4zyQrsOrTRlnCnIpqCQpe+X3e8XQqDgZaGjMY4oFyb8wPs/Yw
; caGi1Iw8bqj2RNMDIW3FvzFfWfDVJY9raz3uG8VB8qFseKUSACXqvLQCSjka8nBjNJm0Lflktp0F4D
; RI5GhoU54YbcZ1mL+5e5i4AtTEQrWhT9553fIjNPKKhdM6vjKtLHz0LVMNrBJ90An4DIChHajO4//S
; RDQ4HaalijFA+OAijwiIeJlcx/4erUrDaPPFotdBG9p7mNjC+ZXHDQHOJ01zNHgmBiR7MrKcolPgRQ
; MoSNCEaDptQqQ1rGXgcyEgE0NjSKMSBOa6ZeJurjbUlrnaWYG9CX2hlTzgbMkyuXXUerQtbUCBcTsd
; jcoAFISARzQcc1gkFpYnQMEKK8I1LIpS9UvV1wE84pN445p/xgAXAl4d87hkNHh2LE5ewWjtNCCaAx
; OG6dXLX8qYxDThOjTQl19+aapyCLdUeX7umVgkBRMAjiYA8irhq2t4BQWCo0EhQTfhiwJQjobidvoc
; rwkQqzLDgIHplXYFRKprqbABkljYfdAwX8XR0O5NHKc0W9oeJk3WeoJPVezUd3YbvGAA6SBpO9cxkK
; g0ikxKmTma3guiNJp9D7yCgHw1JpPv8yBLW5fKfeLkYObd3wK3vPms8+aFV+qUx5139h/MczHoqs7j
; th1ANJC2qs2bgwGJdpovMl9DkyoXnQaX1iczYeY6MfAxSHA0mD7QIVmQMpDcPUwkTcrjLpjyRzOgGX
; Csx123bl2t4MsEUGGP2AyC9kn2hTJ8Ha4yewW780DiGHKT7DdHgtwHiSvAqjxuKLTExTTHbZrJVXiF
; vmDNdrvyuJUA6OtgJvzK44ZqGFvQgKpCToOKBgJulcnHaDOETAUbIFHwKkh890FhLHncIg6GguQvLv
; lr4xwNND3VR90Kr4TIqaee+l8A5Whw44ATC4QPMFU+u/MtBYO1yU7RaxBA5X0YbHxJvtc+FxoVR0OV
; OEXO3zRHg/CKtsMltFRX8CZOnEjfrR6xYAMD2vwQda1NHsuANzg41sSqQNR2aORolD0/YBOTRBsqn0
; xxAyEWBlTR8zbJ0ZDJZdBRqRy7Mq3TWm9kemPgMwAy8ScHqKxDlfDZkODMYA61f3PV10BrE9siZEM6
; rSh8113wl0YWjLI2hcoie+OfOsI3YvWGBJ8BUPvNoZUwaVWDgeAoALoqllUMUOU1AJsQDeta2KmLDo
; nV5k1zNLhnnrHujoar9UYBqCJLzcu0yr0KKDgPDo22VVOgWXV8VZhgFYzaVTSYfPLJpJm4Tln46prH
; RXmwNUrdHY00+AyAdicARNqLRmJF1cJK1bnf28UARa+B2SW2x/zVHTScd/v27Sb4itblfpqu9Zb983
; fJzMGJre1wu53HzRIcjSzwvADaWoXRhfYqAgZAyKRnaVOg0FYZMdqQY4kBImlgSZgPEo7AUeE6TdV6
; ZDT0onCmGHXI4xbVerkAqpPRMIAUGipR8aryuKFAkQXRSrm8Y/Ge0XrcWyi0gMfGSmwrx/Pwpsim5X
; EZaORxCcBXvTKtYhl2HY1CACLK8/LAeUl6rUxTPjgUPvv32sXApzU1t2NNbkj2wzc4MFnD66/KhK+O
; 4RXanvK0uuVxi2q9YAAlqlDx5V/5t96jVibupnPJW7bnjSoY1ZqOoudvWniFZyWL8/nnn9cyj1sWvm
; AABYf7ohGtTAvN44YKWpQ5KFpReVxVwBQ5X9MKRmURgK4TK9O6AV40gBJtXQaI2k2+6pieOoDGJ51W
; xOSGwFfXPC7WRtvc9TJ8hQBUvJDQBuahrNn1iXbpwgsng6KC117Veog2/mG7Y/bqqSt4hFdG/j9cFr
; xCAGqrDa3H1bphgKkCPDQpUJPFsIHjOsonh2jbJuZxaUMKK3rR0SgNIA1ERkH7N9vfaY0BWrFMZoOU
; Eo5GWk6ae9Ca4LT5ZtPyuPPPGWfak3UpvEm8zuEVXx63IwCSUWCul7VqDDj0opci1TR4vsAXkiPWPs
; 8qeG2iydXWtuziRbamqXnctgOId6v1uCGmD82kOr8Q8Bj9xPUw4zGBa65DzFG7ljbR0WAqw4t+ejW8
; UgpAebpZFc1Z5lr55CzHgRwxjgbHFvWiN149oVHhFRWMUixa5/CKXTDabhlwAVPBaNmSKeWT0aIuoJ
; TTM+/Jy+NmSRM3/mHQsdi+SQWjbQdQ8ynMAqZTL3cuCoYtnFN5Xu0jw1yvTCkWjkYT87gURVCZ08mN
; f2Jl0qRJw+1wNDIBZO4FhNTUqWy+CvhsjYc2XbFihalIcZ2HqrReHR0NPTuvvOjGxj911XqjANTbHJ
; nvsbCn6nJ5zsdcD0dDbzkqAmATC0Z5ZhyNJheMth1AvbNMq+LK1AG6gqklj6uC0bxF303Xeu4LXOpc
; MNpt8FoAutqoSB2gKwDN7qLEuXzzST5DG6at522i1rt33n8WXhEsZ/eG4yGPWwmAafO20DpAV7TxD1
; o0az6pRd/ak6+pWg9ZOHW8KR5AKHytK3hV53HbBqCtyfCK8zbrEbTMIVl6GTqP5DfKJwNuHnx1zeMy
; rWA97vEeVK4cQEHi1gG6oo1/9HbJGI0p0JfPH0o+Wva/jXM0WKPxxRdf9OFrF4DuvI35of15kY1/Yu
; Z6dQyvaNDxmtJeLxitDYCat9kvhmHbr6Ib/4TAV+eNf3iBSzteZTBhwgQDzsknn5yccsopyWmnndaz
; 8EUDKJPMnBCTo8Xgva717Dwuu3G1a+MfoDnhhBNGyYknnmhADD1HJ/O4HQcQ+JjzsPGP1msUqQNsoq
; OB5mdJZDvzuD4ApcXOOOOMntF6hQAkpYSjQaxLwNExen9ISB1gUzf+wbPvxAtcXABtmPJ+2408bscA
; xPkgmZ62AMne768XTO4NF55hwkJ4/2z808k87rhx4zCjLZhG2nWkeYeGe0nrBQNIag7wCBbnzfWy6g
; Cb5migzSmc4P243QqvZEHXK/BlAkgZFRmN0IVANrSqA2zqC1xYGFTnMvnQjX8aCSDzO4pFKRotWhfI
; OTYv+FOjtJ4WXvXSxj+NANCuzyOlFLvxj8/RaGLBKMF0lkUy360rfGdFbvzTCAAZ9ZhZwivsMNquXQ
; iQOm/80y8Y7RKAaD3SSZRPldl/pYnhFXZ36OWNfxoBoApGMbtkOGJ3r29qHnf9+vX9PG4dALTzuMpu
; 4MGG7MWyfEbz8rg8H6906NQr6fvw5QDoQkW8jxAMc8O8BURrRuZ0Xy6qP3yXDP3N5HF593DdN/5pUh
; 63LQBKMMVoCxyUtGoXAET2zqlvHpfnYMUf63H74ZUGAYgQnmCNA/NDn3csAJEXZtYHPMHHwKFw4ttv
; vzX56jrD12vhlUoAlLDJNw4KzoqdkrMBfHRKfcDj3pg+PPfcc8f1xj89AyCCBsQkU5akNR91A9De+O
; fgwYP99bi9BODgryk2nBMqX+jkugBoF4yyFrcXXuDSBzBDE4780Gy1UQcAldFgntrf+KfHASQ+SPaA
; ahcKUbsNoPK4pBB3795d6zxuUwtGawGgCk7JF2OCFRvsFoD2xj/btm3r53F7GUDiaCw4J4zhvs61Gw
; CqWrnXX+By3AOozcfRemkbg3cSQBwNtB4hoR07dvS1Xi8DqH1h0DJZr2DoFIAKrxAUP3DgQO3zuKzp
; aBIEXQXQrnrWNrLsahXycphOAAh83AdrNNh/pa7gEV4BPv7uOxsRALLug7kdnUy2A5NLMUJIXWA7Ab
; Rf4MLWtnV/gYvg6wMYCSB1cWwpNvIPo/ViKqLbBaDyuNwTK9Pq/gIXG74+gJEAnn766cbL/eWXX8xi
; pJgXzVQNoJ3H3bRpU+3zuC54fQALAMiWD0DI/w8dOmTeKh5aFV0lgHI02K+6XRv/dAI+5oJNAqDrAK
; rhgBDZsGFDcvToURN66YQTYudxV61a1baNf6oQ4Pp1l9HMY5oEQNcBtDe9kTZkzoUWWrlyZeYLa8oC
; uHT6n1vvJmlCHjdN6/UBLAEge5EAnd2IMsloQ/Y9xhP1VUWXARCTS30hAWXCK3UuGA3RfH0ASwCIjB
; 8/PrG1oUwyDsq+ffvMsk0C1GUBtPO4W7durX1GI0Tr2ULRQZMAqA2AElsbug7Krl27RlVFxwKofZUx
; 8YcPH659HjcWvj6ABQAcifutdiFEG9qNKm1IzPDYsWMGIMxyKID2xj/M8+r+Apci4PUBLAgg/xnJsQ
; 75IPQ5KNQCHjlyxOyjEgKgwis4G/v376/9yrQy8P0qfQBjAZSceeaZw1kmWdoQGDdu3JgLoPK4y5cv
; T/bs2dNxoGLhC3U0suR4W9dbKYBImkn2acMZf5+Q3D30P2MAlKNB3d7OnTt7ztHoA9hGABFMcow2XD
; D4fy0A5w6eZEI27C/IC1zqvjKtSvj6AFYEoCTGQUEb/vTTTyZcs2XLlkZVr1R53n4euEIAkTRt6DPJ
; /B/n5HiFj53t+wDGyb8Bf6H6N1VP6DsAAAAASUVORK5CYII=
; thumbnail end
;
; 

; external perimeters extrusion width = 3.00mm
; perimeters extrusion width = 3.00mm
; infill extrusion width = 3.00mm
; solid infill extrusion width = 3.00mm
; top infill extrusion width = 3.00mm
; first layer extrusion width = 3.00mm

M73 P0 R5
M73 Q0 S5
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P2 ; nozzle diameter check
M115 U3.14.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 X1e-06 Y1.5 W100 H3 ; mesh bed levelling

; G1 Z0.2 F720
; G1 Y-3 F1000 ; go outside print area
; G92 E0
; G1 X60 E9 F1000 ; intro line
; G1 X100 E12.5 F1000 ; intro line

G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.

G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion

M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0




M107
;LAYER_CHANGE
;Z:2
;HEIGHT:2
G1 E-.8 F2100
G1 Z2.4 F7800
G1 X1.5 Y3
G1 Z2
G1 E.8 F2100
;TYPE:External perimeter
;WIDTH:3
G1 F175.043
G1 X98.5 Y3 E207.34968
M106 S84.15
;LAYER_CHANGE
;Z:4
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;4


;WIPE_START
G1 F6240
M73 P9 R5
M73 Q9 S5
G1 X95.998 Y3 E-.8
;WIPE_END
G1 Z4 F7800
;AFTER_LAYER_CHANGE
;4
M104 S210 ; set temperature
G1 Z4.4
G1 X98.5 Y3
G1 Z4
G1 E.8 F2100
G1 F175.043
G1 X1.5 Y3 E207.34968
M106 S170.85
;LAYER_CHANGE
;Z:6
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;6


;WIPE_START
G1 F6240
M73 P19 R4
M73 Q19 S4
G1 X4.002 Y3 E-.8
;WIPE_END
G1 Z6 F7800
;AFTER_LAYER_CHANGE
;6
G1 Z6.4
G1 X98.5 Y3
G1 Z6
G1 E.8 F2100
G1 F175.043
G1 X1.5 Y3 E207.34968
M106 S255
;LAYER_CHANGE
;Z:8
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;8


;WIPE_START
G1 F6240
M73 P29 R4
M73 Q28 S4
G1 X4.002 Y3 E-.8
;WIPE_END
G1 Z8 F7800
;AFTER_LAYER_CHANGE
;8
G1 Z8.4
M73 Q29 S4
G1 X98.5 Y3
G1 Z8
G1 E.8 F2100
G1 F175.043
G1 X1.5 Y3 E207.34968
;LAYER_CHANGE
;Z:10
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;10


;WIPE_START
G1 F6240
M73 P38 R3
M73 Q38 S3
G1 X4.002 Y3 E-.8
;WIPE_END
G1 Z10 F7800
;AFTER_LAYER_CHANGE
;10
G1 Z10.4
G1 X98.5 Y3
G1 Z10
M73 P39 R3
M73 Q39 S3
G1 E.8 F2100
G1 F175.043
G1 X1.5 Y3 E207.34968
;LAYER_CHANGE
;Z:12
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;12


;WIPE_START
G1 F6240
M73 P48 R3
M73 Q48 S3
G1 X4.002 Y3 E-.8
;WIPE_END
G1 Z12 F7800
;AFTER_LAYER_CHANGE
;12
G1 Z12.4
G1 X98.5 Y3
G1 Z12
M73 P49 R2
M73 Q49 S3
G1 E.8 F2100
G1 F175.043
G1 X1.5 Y3 E207.34968
;LAYER_CHANGE
;Z:14
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;14


;WIPE_START
G1 F6240
M73 P58 R2
M73 Q58 S2
G1 X4.002 Y3 E-.8
;WIPE_END
G1 Z14 F7800
;AFTER_LAYER_CHANGE
;14
G1 Z14.4
G1 X98.5 Y3
G1 Z14
G1 E.8 F2100
G1 F175.043
G1 X1.5 Y3 E207.34968
;LAYER_CHANGE
;Z:16
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;16


;WIPE_START
G1 F6240
M73 P68 R1
M73 Q68 S1
G1 X4.002 Y3 E-.8
;WIPE_END
G1 Z16 F7800
;AFTER_LAYER_CHANGE
;16
G1 Z16.4
G1 X98.5 Y3
G1 Z16
G1 E.8 F2100
G1 F175.043
G1 X1.5 Y3 E207.34968
;LAYER_CHANGE
;Z:18
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;18


;WIPE_START
G1 F6240
M73 P78 R1
M73 Q78 S1
G1 X4.002 Y3 E-.8
;WIPE_END
G1 Z18 F7800
;AFTER_LAYER_CHANGE
;18
G1 Z18.4
G1 X98.5 Y3
G1 Z18
G1 E.8 F2100
G1 F175.043
G1 X1.5 Y3 E207.34968
;LAYER_CHANGE
;Z:20
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;20


;WIPE_START
G1 F6240
M73 P88 R0
M73 Q88 S0
G1 X4.002 Y3 E-.8
;WIPE_END
G1 Z20 F7800
;AFTER_LAYER_CHANGE
;20
G1 Z20.4
G1 X98.5 Y3
G1 Z20
G1 E.8 F2100
G1 F175.043
G1 X1.5 Y3 E207.34968
;WIPE_START
G1 F6240;_WIPE
M73 P97 R0
M73 Q97 S0
G1 X4.002 Y3 E-.8
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z21 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
G1 Z69 F720 ; Move print head further up
M73 P98 R0
M73 Q98 S0
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M84 ; disable motors
; max_layer_z = 20
M73 P100 R0
M73 Q100 S0
; objects_info = {"objects":[]}
; filament used [mm] = 2073.50
; filament used [cm3] = 4.99
; filament used [g] = 6.18
; filament cost = 0.16
; total filament used [g] = 6.18
; total filament cost = 0.16
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 5m 52s
; estimated printing time (silent mode) = 5m 53s
; estimated first layer printing time (normal mode) = 34s
; estimated first layer printing time (silent mode) = 34s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; bed_temperature_extruder = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600\nG1 E0.3 F1500 ; prime after color change
; colorprint_heights = 
; compatible_printers_condition_cummulative = ;"nozzle_diameter[0]!=0.8 and printer_notes!~/.*PG.*/ and printer_notes!~/.*MINIIS.*/ and printer_model!=\"MK3.5\" and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_perimeter_transition_distance = 0
; cooling_slowdown_logic = uniform_cooling
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; custom_parameters_filament = ""
; custom_parameters_print = 
; custom_parameters_printer = 
; default_acceleration = 0
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 3
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 3
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_abrasive = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 0
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_length_toolchange = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = nil
; filament_settings_id = "WAAM Settings"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = nil
; filament_travel_ramping_lift = nil
; filament_travel_slope = nil
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filament_wipe = nil
; fill_angle = 45
; fill_density = 20%
; fill_pattern = gyroid
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 3
; first_layer_height = 2
; first_layer_infill_speed = 0
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil
; infill_acceleration = 0
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 3
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = ;"Generic PLA";"Original Prusa i3 MK3S & MK3S+"
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 2
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 3
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = WAAM Multi-Layer Slicing Settings
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = WAAM Settings
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 12
; small_perimeter_speed = 15
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 3
; solid_infill_speed = 20
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "{if printer_notes!~/.*(MK3.5|MINIIS).*/}\nM900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0\n{endif}\n\n{if printer_notes=~/.*MINIIS.*/}\nM572 S{if nozzle_diameter[0]==0.6}0.17{elsif nozzle_diameter[0]==0.8}0.12{elsif nozzle_diameter[0]==0.4}0.27{elsif nozzle_diameter[0]==0.25}0.85{else}0{endif}\n{endif}\n\n{if printer_notes=~/.*MK3.5.*/}\nM572 S{if nozzle_diameter[0]==0.4}0.035{elsif nozzle_diameter[0]==0.5}0.025{elsif nozzle_diameter[0]==0.6}0.02{elsif nozzle_diameter[0]==0.8}0.014{elsif nozzle_diameter[0]==0.25}0.12{elsif nozzle_diameter[0]==0.3}0.08{else}0{endif} ; Filament gcode\n{endif}"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.14.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 X{first_layer_print_min[0]} Y{first_layer_print_min[1]} W{(first_layer_print_max[0]) - (first_layer_print_min[0])} H{(first_layer_print_max[1]) - (first_layer_print_min[1])} ; mesh bed levelling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\n; G1 Z0.3 F720\n;G1 Y-3 F1000 ; go outside print area\n; G92 E0\n; G1 X60 E9 F1000 ; intro line\n; G1 X100 E9 F1000 ; intro line\n{else}\n; G1 Z0.2 F720\n; G1 Y-3 F1000 ; go outside print area\n; G92 E0\n; G1 X60 E9 F1000 ; intro line\n; G1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 3
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 15
; top_solid_layers = 6
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_short_distance_acceleration = 0
; travel_slope = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
M84 ; disable motors
