; generated by PrusaSlicer 2.9.3 on 2025-10-23 at 10:22:03 UTC


;
; thumbnail begin 160x120 15652
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAAtoElEQVR4Ad3dV7clxZnm8f0ZeuS6Zy
; 5nRl6rZ9aanp5WS6IbJCGoAgoojDDCI7wH4QSyyIAQIJBB3nuD7MjMhdbiTjdzo6+zu34pntNxoiIz
; I/c+gl19EXXq7JM7M8w/XhdvRK5OPvnk9SmnnLKvnHrqqeuzzz57+Pn2t7+9WQ4fPry+5ppr1uecc8
; 76ne985/od73jHXvH7VHHfd7/73esrr7xyfeaZZw6/p7zrXe8aymmnnba+5ZZb1l/5ylfWX/3qV9cX
; X3zxvr/NlfPPP3/9xS9+cf29731v/eCDD67POOOM9emnn35c8bl6XHXVVetDhw4tKvrAc6677rr1BR
; dcsPdZXfTl5Zdfvn7Pe96zPnr06PDM1nWtctZZZ62vv/76oQ36uvxbXZ9zzz13feONNw51af19rOgH
; Pz3n3nvvHZ7T6ivlkksuWb/3ve8dxm1uDDJeKeqkn93D84z3qoZP52j0GHg1aDpVeezC/7q+7qz/NQ
; mdkkpcdNFFQ4Nq8Opy4YUXrh9//PH197///fV99903fGeswemkW2+9df2DH/xg/YUvfGF4Vt2JLZAM
; 2g033DB0/hx0AQNU11577fD/OZAMmDZfccUVw+Tr+Q5Y77///gGMXmCVq6++emi3Z/YAqM0PPPDAAN
; bYRC2LCaVOmXQ9IGqLvvKsEs49AAHlxv44B15dnrz0tev/f91qKNef9Q9N8JTzzjtvkJqeMwZcWdIA
; nWpmfvOb31x//vOfHxpTQ6cYVLD+8Ic/XH/0ox/dN5N7BuLIkSODNDOh5sBwnZm8BAyDS0qB8NJLLx
; 3+35KGwHHN+9///mECLnlGiu+Rhuo6JTVJf8+ZkpotCH2ujkD3vTHB4PPLLrtsuFZb6zEeAAzVYFoC
; H4n348v+Zg++lJ9c/jf7wFORqCAV7wWvLhrx2c9+dlCrN998874O0ZHf+ta31l/72teGvy1VpSUk4D
; B4gKzBAB34wNMCrKeYKPpCnwDFffM343DXXXetb7/99n2ft0qP+ibVPce96r/dfffd69tuu234/xJ1
; XRZCxTP0Rz7LeGkLqQfu8vN9ALqBxiwBL9Lth+etjoMv5adX/Kf1DUf+9zCIVEKk1lLoakmnUR/+8I
; cHCB977LHh9w9+8IOD1PvUpz41qLclwI1JKvW96aabBrVp8NKZBrMXtKningYmNhFb0k/SCJzb3r9s
; i/vFvPC7NnmOiVaDvAmI7qFvojn8nc1u3I3/lGpetVTulLot1esjp6zWnz+8Wv+/y8ZB/MI1/7Mpen
; vAG7NBNBAc3/nOd9Z/+tOf1j/96U/X73vf+4bnbALcGIQkg44lJWLcHwR8JYQkB7MEECZSnJSDLnFQ
; 2NFK7dC0ylIYTX7jwj4M3FM2u7JyUal6e8ArAUzpkYbbglcCSE397Gc/W//85z9f/+QnP1k/9NBD+w
; BcClurkHpmMZWuY0mpKZg2KVTwhz70ofUdd9wxSEMD57lz31sKoLrrIxOVNCSZetT4EhgBqK9MWO2o
; JWUTQAaiL7LVesGLc1ECGGk4BqHy2IX/bWPwylDD008/PXi5pIbfNVioRthFWzYFroTJgBko6ookBA
; XbL6GjbQsASNcPfOADA4SeQfq5vzFhGvlsk3vXbfEc8JHg7ulna0JtCqNnmDzqHu8+EQJ/q8dyH4Ag
; UxFqwM164WsBmDKlkknDpdIuBQBsP7FBcJSSjv3x1FNPDeGaO++8c1+HLpEUwNB51Ai4y4HVuWa2WV
; 7/rbcENF59HIAaTG0xmOD3+6aQU7PCOOKpJlDZTs/NhPL/MRtyDkQTJXHQGk59ZJxc03Jg9gBUXABC
; F4NrCrw5AOdUsnLj2f/YBV1m2Mc+9rH1j370o8HxSGPropNJFJB+5jOf2Qtz9Eg8JeEVAI5JnwAEQq
; D4vbeAiXR7+OGHB5CnrtVG6j/B6/rvc/DVzxmTkhwfbZmyPce0iGckrDampn3umoRh6rFe1RKP9+Ji
; dI6B1wNgj4Py+EX/fRI8xQB84xvfGEIs7L6p2ZkOM+u+9KUvDU4KoObsNQOk3b5HG4yBVxadTu0w7E
; maOfhMBnZeVhp6gHWdsSClmBYA7vkeDSDE0iulPYdKDqxTk1U/uz5xUN/vsRWZGWWg/zgAS0mnEqLi
; WY5rFdfMAdjnoLxsfdM5/6c5c0TnORik2VhweKyjSJBHH310sBVJzzFVpkPMUCXXLJFoOpaKi63Yug
; bcJHOe0Xv/8vu+m+D12LXqQOol/NErLVPAzvSo1XVZQOeauSXFFoSJSyaAPwA4ZufxVM08A18vmZmN
; GtkLYK80TEVJoWeffXaw5xjP9bJVr1r1PVKTBP36178+qIxSomW1YAye3hKJwOg28Ck+d39QmBDl35
; YWphGJC5Lcq4TUc7KiMVffKQj1PZVsjEtVDUpCCRPxoHtsxRaIJlIclNWcrZfF9lQceFlMXgJgn4Py
; svXHbj53kFoAVMml3uuYPUSK/vjHPx4W9bMclhWNJdJorBggHUsaGjwgeFYcgG3gK59BIBgDzwK48Q
; FerynQA2M0oOd4pvboq3rVptdpaUGorqThasrJSPEA9otiJiaKvQmAPeGaZz9w7fCcbaCrO1SDqcHv
; fve7g5NCjWwC2lwxWMDjLIHkIMCrIcwKCuluzRuUrWu3hZHqD9xU7hh824C4moIPZNSvBpIivEO2iA
; eBcFMAe1Typy9+9dbQlSUSChyyZIAoa2Zb4Go1ec899wyORgLYPvPsbUv5HDBohwB2Vh1MsLn6LYEx
; cVBjrp9ojNKO3hZE13CWVmNSD3wemNBM4jY+I45VcBsAexyUn135svUtR/+pG7yxzjRgVAqpof4kCM
; fE+rHsGWq4V/q0isE3QQERtRXVJdZnAh8EhJlEnqMt2kVKMVUSvO5V91PwJQ6aYHg+Iwlrz3oTELHD
; QeRgrlrgAU3DklPWWrFgjB4EgH3S8DWLoSs9yCQV1DAxKTgnQjzxHKdAaxUQkBBZaWj93YRNxsim4I
; EczCID9XOAov4JXi+1OcuJqp6kXcue9BxSXZ/WKrsXQn3x5S9/eXAwAb2q4fMFjdEQonJq2eygAOyV
; hrcefXMXeIrB1o44GmOdTzo9+eSTg4NCsuj4XiAS9gC436cKxw1AvjN3bVkiSdmv4ADJWH20hcZK8L
; qlvscKyaodPfFGz0iYrhYIYxBmkYCD+bnPfW7Pxl+V2chmFnGexNS59dqDBrDHQSEN56Qeb01njhnn
; 9eABlE0lcG1NeUxlBopINdkrwOqFiepRr2xl6ClUoYnRek6rfsbQ/UlD/TBnT/oOmIy7dvXai0k8SN
; hnCkTqWx4nlSsTp5SKK+CRdMRugr29yQJ/DQBTplQyadjyWnVmbBWD3WO/lcUgcFBIQ85ECwgdbn2V
; BwrcJdIs8IKDNHSvKVhNCoY6abFEYibMVAavW+1N+lQycJbair4TlV06KKWW4pBx+Jg6yXMsVfIqKw
; E6ZiqtulX+mgDOqWTltvPfss8DJS3YrenMJfZVCdgjjzwyOCiybgJJBpXUA1Br8F3TWwy+rGf3rP/m
; /qSen5tAnhIHxTMAHUD91E9ZeuxR01MgAgvIpYPC1HjiiSeGlLmsRLVsw1UWiZekSCWG89cGsMdBee
; o9r9tnv2wCXauQUNL7GcucDA4LB8CALQFtqiSTJOEaQsAaLgkL/LHvLYEwDgrg9E/Mk4A/pZ6XgKju
; +ow3rr+YMvqOUJiyDVdTGatzmSovBoA90vDX1/3d+s53n7Q1dLU0o84ZzM8///yQa3iQ8KUYOBOIbf
; SJT3xiL/yx9D5zbfGMJENMqeVtQDRp9Ndvf/vb4Wed2NEEcBPwXgoAIw2nVLLdeZtC15JOJAV1nBSv
; b3/723tqsQes3kJi2OfC3suqwzZQt6QgdasAnEQkDVuOzBIQS/hiP3M0sgSZ7adTEK6oADdbCh/9/W
; IDmDKlkp+76uUbAVfbZ5agSIzAwE42q+0/8bclgI0Vz2FTsgVJD6BQjX5nQ5XXbgpjEmgj9dwrDkrC
; NduA6Lv6wwRlsiSlKwsWia+Oeckrv3DDGaxL4HspAZxTycrtF7x1sZOQfcscAOq3BgYkH/nIRwYHRb
; KE0Mim8Olz9wJD7L8STPZUdhOOlTkJ7BmkXuzJsh8AnuwWdmHpRfeCmCQPk1Kf+XutlvURaaiNLQgH
; FZwUGcT6wxh49WaflxLAqOQ5B6UHPMUg2bDDFmO7TA18jgwBImm1BDz3zs40oE1dlx156tZz77QFXO
; oYuMfUdBwUkw4oJaRzIApDWUESO02e45ht6L6kMGBrabgqpZ0HZ8ZMgaf48ksNYI80/PnVr1jfceHb
; Ju000o4NZgL2gmTC2ocsZmg9OSp0quQ5JA/A5q5XgMEUaEnkVuHtJkG2V3VH+HhGwjVjIJo01nFJvU
; 9/+tP7gtdznrIJkazoJoDZZEwsmxnJXKjhUwnreY9f8rqdgbBHGtbOgc4mYdhhtc1VljE4fJ/UjCQA
; 1th1ILJsB6ge8MoCbs4Jp6hW1ynJzCY1awneqwF8N+GaFoTqQPLbm0PyT9mGZ01k2ZCGSQJetew9kK
; XRKlfC58EqwOMheq9/16t3BsI5afjcVa8YwjUGBQi8Wx5oOahL4Ygae+aZZwapQMKV0s1zfOY5INnk
; /oGYhAJyCXEkeLJuxgDtATEOChDjtERVmzzG3V4b/kKPgzIVvPYMZTXmbIAtnowGqkwW7YUmVHZvn8
; ChN6/vfefLdgbCuXDNl6//hwEKNsmm0NUFXCSpxXYS0UCawByNqLaxsuQ5pBOYc+YKleY5nt9rPsyB
; SDoZd20g1W13/cUvfjG0b8o+XAIh9astqzlHw4UMzl/96lfD3gpiPh5M7dXcsGPScEolsw03kUJzhZ
; q0CvDHP/5x8BANZs/3lsAZ7fTxj398D8T6mm1BBLRsa3E9kg+IU7bhJhAOKngOPpWgWqzrlQfnjOXm
; XXr4n3dKGk6p5F9c88r1XRedtDFsrUIdS8e3jmwdlGreFsK6gI4gYKtbumO3jU2aTUCkfrUBeMYd7N
; kMdVAQ+ky/rMbgY2eQeAKMQga5iUabDbU7XT/ghtNeszMQzjkon7nsDVtBpxgcGTQSU9lIJAg4nGlo
; TTRHYWxT3JetB8DYk9nZRy3PeeI9MLLxjbs6gxyQOTnD5FKHnnDNFIS+l1zNVQ0f6cazI3pF/gFX78
; fI2SJ+jiWHDkmOZ7xlZyCck4ZU8l0X/cti6BS2JFsv2xnzuaL/Eqy11guY8u9lmXoWKccB8azW331u
; KS+OyFII1ZtKV0+HgAa00kHxDMIn6f+bQBjzIadKrEr4PETioABrsoPH9mN4QJZaWvDtZdoeg/BEcl
; BIwzHQWoXkiaMxdo3BJRlpEw4KaTJ1z/q7wM7+5SlIXUtqJc2qF0TjKNniueeeGzJ+puxDE6gVrpmD
; 0DXJ1fT8PRsw8Kl0efDP3C60PSn3wlqjm46540MM6fTX7gyEypyDMgcGCWGSUrPA6IFJIoAlPLZhNp
; FPFQNGJWa5bE5KZrIQCqShOs45VcIrPHemguf0OCn+5tocSun3KQg9p87V3APQP5/85CcHlcvw1NAe
; +MqiMSDUYUdGspB1zB1XHFm//9Df7gyEc+vJd1/8r00wSAzOGUk2pVLHwKXqhLPAaADra3KOCmnGFt
; 9EZXsOlQ3GljQEEAeJ1FMf1yz1lD2DSi4dlDoTqd5rUtuDq0TxzeQ6XaZ3F1pELMJzdFlZiWTMRmTf
; tEPScM5BefryN+4DQ7KodKOA4bNNSnbk8TT9P88wYKQe6VLbk0tB9DeAcFzitPics2TMSb6oxE3DNQ
; nElw6Kcfe5Z09tChsAFC5gVPZs/h6Dr5R45V5YjVUJpfSclMvOfOvOQDgnDYVrHr7m0CD1DFgyi7ct
; JIfgPgitK1NT4NN3SyXrFIygzsmonlOGh3qdlDEAy4RXGiGH0ZPe9eauFoSrVq7+JvCVEOoIEOZ8uq
; l8vPtOffnOQDh/3vX/OBDwypKjPHifwKBBWtdtCyFnidr/3e9+N2RFb+Ipz0FIAlq04MiAr1bJTQBr
; 6bctfCpqJmTfQUITU3l5Nx3anaQGZdpBeeX6nktOPjAAmS2kHkCsr7PJLBNOSdklILoPLx18zC3jwU
; GZS4pYCmHikVRxnfA6BeEqR/i3slaXwqcSGpid9YpOII5VbMqruvzISTsnDacclPddevKeBNukUH/6
; CnhgcC8ShJqnkmUXx/vdFESmD0fnl7/85XDfQOnZoJ9LC+uBMMkQtaDx/+zIq/cn7wOQ1HOT8p0YS+
; FTEZVwjzyslHhHX8hTS3LluY2cvJSbd0gazqnkZ65440bw6StSyADp8/Jv+i+7ykQm2G5zUrTlRVPr
; nAwrGokLthwUDpDnbgKhe7h38ihrMyvhmhzpF5V8HIBg8wuxmXef9cAXb4fxPLfbP1kWZl6ya8Yad8
; UxaXj/DknDaQflVYM07JV6+iorGlPX+rtEV7YhRzHLe3MgkjiyV7y+goNTxijHHBR2G1CWQEhzmih+
; 1vZgXbI/2bi7XwnhqrT7QBbVoHJz8OWA6+SH9Wz+CbCt5Mq64fe/6xU7A+G20tBAAY/E0F+90pLDYD
; de1pOnACRVBZRJTlD1Oiix35hKrpkCMJIzx3K0HJJWcR9CKi+qDISrls3nRjoqx7HWRUUQnbOCe+Er
; 1W4GxAxswefvjPG7rz53ZyCcl4avPE4a6mx9FSlTq9yeYuCETYDllAH3KMEjCKwz86JlqpOem8QNYx
; oYk5YkNHFIvRwNN+aUtFjAiL+VByj5fTVm8/mCCpkVHlTG+bLBpI5698JXzib3Z0PUuW5JGNUxV579
; LzsnDaccFNIQJMAwYNpoUAPkJhD6Tk54la3CrsqKiSxlCaN56U2PkzK1nqzOOQMyY+J5Pu/ZLjoGYL
; kqlpjhasrpSPYC58HszaYSFdsWvhT30jgSQoWskYrUtzrplsOv3xkIlSmV/Kv3/u2wuqSjSY6AN1Z6
; QTQ5Iw1lrUgcyX6UpZ7y3HpybFUCJ0KiNzQzB6Fr3HvV4/HqIEtQ7JE6rtOrelsVr6WeOJhGT3XMVe
; f8605Jw7n15Hvf8/ZZ+JbCyPQR1/vzn/88BJYT6tgkXDPW177HdLBOHHv9IAEMO6sp+FyUxWSzWMmW
; v4OCT4cKNWTHmM4lcX0+lRJ16xlv2BkI5x2UNy2GsAWizwgBKpjkszeH0+H/We89CAg9i6bLuBuTJL
; wuCVBPAeh3WnU1Bp+bZh23/LLPSat6j8A5G8BH5QqQ1tnCRDOVnCyLsXLVuSfvDIRz0vAv4ZpTNgYx
; YRnhFZoiYRwOQRJerfPWDkoPhOUkd9+8uTM2oJ+cBg5KNnJtIwUzxk0AwadhoCCR6rSq6O9sBdSwpf
; DF+eBokLBTyZXJvG4FW1NOrHDNcmlI+lgZAR8buSUZcz5LXk+2BML0dzJnSL2MQ+kFu5Y9mBcQbgKg
; e2MHW1jaB2DEYk5oasFXql4NUmGzpRc+FaBuzabzZ5Irs1ZKGgK1BV/KLqlkZQpC4Zoe8AxSdqaJBX
; Jo5mzDrCfbQpmVlTkA463nrZflGLSSWDFCSi7xiH2X1ItWC0urcsd63guRIOEUfOVyC2NVA9xjytt1
; HamXM0vOG9kI1OogwE7NbOXqYyr5gf8gDkqyp63jivGVnvQUhPoqbxaV3W48xyAc+uyYt5sUsDFB0I
; oJehbhk9N1pwBUZ2MOQJ+VPK384+F5Jf1YRvOc06GDNKRlI6isnXU5+XMJfCmZ4aRhFu9T0vl5s88H
; L9udXMM5lfzZK/erZG3IOi7nIk7fUk/ZWFDbvGXhoBpAz8mb4EsoewEshUprjT+CKFKvfDvAPgDLd4
; JtCl+KCgE5NoLi4dKBymDzUvjKzjOjxQkTiE2HDy9PPOYVZvPOiSQNOSikYRwKQWWxPmbHNuEafeUA
; IQ5K1oXTh9lr0hOWmVoj9jMHKEXCKZ5v7LP+O+YNr1zYWuedA3DM6Qh0Zp3wSg7+mYOvF8CkLZEM1L
; 7/A9IGoXqB33MfOO2VOwPhnDT83SNnD/abUMumoZpWMQ7Z60sTxdFYEhecS1JwTV7IQyr6GSCnwjEr
; AzoHYI/0qzMlGM+KyhwkfCk6n7RjJ+Xc4xq+lNvOeuPOQDgnDZ13vSR4PQdftARVaw/Kb37zm0FT+G
; wuLLMEQCUboWi88ijjSQDtB01C6rbST0XZaVnH1RgAljlnBwFf1isZ52YdaZt8xhq+lGuOnrJz0nB6
; PflNBwKhvxuDvBLC2LAtSUQq/6AAJHSMBZMuwiFJyJMAWk8kmqnKepltifQDhr0A1GFd0eScJbi5DX
; w5Vo0q8f90ssZ7to6YGqxdk4YHEa4Zg1C/m6jZkZg+5HzImmEb6sdtAPQ3YBvbnLIaJsZeyLMPQFKP
; d8pbYvj60hLplweZWTnTuFXZMufM/6cAHIPP7KI+wFZ3ut8ZvOyd/L1VhuTI896+U9JwSiX/8tpXda
; nkui8AIXQ1ltYPzryx0mkY5f7jXgDzQsu8CKcViolHbmxGAVRckDdHsqnGItnlzVWWZHPshEbVS221
; 7ed6z/Gd1obsMQATxskuuzFVk+BtufGmhq8st531pp2BcNsVlDIOqP0kTzTEVOw0BygJ+yTJdM4R8X
; /jCL5sPJqKBWZZlySuteyqtP1cnCAm973eUlne1N9Ivdx0Dr6yDKrwWAflPOop+MwuUi/xsCn4StB0
; DmmYDNwavhTScFcgnJOGf0l4HV9P1lcmt8FuOSNjS3PlAUpOySg1VA1g1p9zNkzvmrCfeWNoecLqqu
; V8cCQkPgpk+kJ5E5UAXd7gOJZoMOf5Jt0ngeUWgEQ3T1rHzhnarZK3AyVcU5dkZfv7g6e/amcgXOqg
; JIsop2ONecNjACbQXx6glCM9yuLePs+Jry1PeG5N2HeYYsZ+SMca83xVymaYpP0kiGmlQUOnslyWhF
; 1AQg3kzLvYJ6QrpyKbcZbCV0pDNiFpqOMCn47Mcw3grqlkpcdBEW0wUROAnwrHTAGYoq/yxqMcoJRA
; f47fmArF9CQl+CzvlFvNxf1AIDjKTiCmp3a09QLYWmbTgToyr8fK2SjbwFeq3tie1D5bJ4ZxKRGBeO
; 357zhhHBTlsTsu6Npr0gug4l4EAGloeygGSFjXT8G3NC8QC7MAukiIxhnRpCExPfbwTQHM2qRG21IY
; G2YKvl7pVxYzmOkgjMOGqeEry+0nmIPSE5DuBTAmEqcPhDY7McXmAtFLAdxLRhgDkCoEX95/QTIRzS
; Qhu+yg4DODk5jKztDYvOzuoAAk+XKesgwOnn5eUdYCMNJwVyCck4Zz+5OXABizRZ+ZtBwTXrKE1wuK
; ZJIeAFuRlHBmLJoAuhEAklNW3tCgSXpkqBrQVGQTAHUAezLruGXYBSTuP7aBuxe+ZPJSu/5fOyB578
; ZUOZHWk8f2J/cCyCzJjrVIQz/Z0HISlSyvbgqgz6l0Y7CqJV+8oRxQ3Soq5PR0wWuHWo4ddDMFoIdb
; M0xi41iwlN2mspsAqKNAnKMhapXsMxOKNCSFpyDcJZU8Lw3370/ugU+fle+Na4Vg/F3QWriGcOpxQl
; oZ0cmW2qeCXWzA3LiM/40FFhWSRczQsk6O6e2Bj8NBnRPBU0HSgBb1WQahp+BLhm/e4D0WAwyErnF/
; bZiCcNcclJ4DlHoA1P6cWjAVA8yKFkYs30p4LQPRc/afZ9Qrbat4I6SAQai/NJX1ooDCxmg2Aicinl
; KrEZGuVjXKdKApAFOSB6gRU/CVwdiW1GsBqGiHiaEfsmehVYYQ0RUn7RSEc8fJTfVvbOKsTM2tgqTo
; K+OehNcpAN2XEPHM2twbzgdkg6nI0rSr0gHhWRLNXu2gQXUDiG+ORjZQL4EvJUdDCKHUm739rlNI5T
; q80gNgihkKQkb4cRLwmIaggqTJP/HwLTsVvJ5TyfWZhiaS9hgX/bdJIoL+46DQgqIXvl/Dl9d95ffj
; ABRs9JBN8v5qDxh4jFROisyYNCovcGkduL0EwKheneaeSfXONk4AJot4UwAj5YCec1J8xgjXLpPM/0
; /EcI3zrvVhzm5ubXtdAmCKvpfeZfUsZ0L7nqhGac61HN7VJnl/U/E/8HDXbSGUXWMvazJgehIP5gAM
; hFlmAyJQEtdbAt8YgCl5e7p0du2xNJm0oxM1XPN/b/gv64/fcrR5gFGv+m0xQOuQgsJ0ea3bVBpWto
; CsQHWQAMb+o269sE8gc+yosG0AHKTPMVUslUzRAWMB6E0hzEGRefFgpOF/BAfl6cvfcCDSr3RAjJtl
; PHtaaIsyBWsUwBy50KN+WwDWlQNI9v2qgJR5hqozRlr7EDYBkJ0G6oQMqJLYbQcBYLYUULdJU2JEe4
; ZnnUjhmiUv5NkUQFzod85INIdEZ1pDn42p3wFADxGu0LFzHvAcgIxasb0689k2Q8s5YBTT2xRAjcya
; cZ35rOFUffIAN4Uwi/G//vWvh5Q0z8nfAro6nEjhmp4X8mwj/djkxr72fE1iE5jjVnvAeyekRvW6QV
; 5ashTAhHE4HmBohWFAmTdHkpCAWgJgXsYHkNoDbuUBJnNjCYDqr34k9tgKCTUMdLO9hHPXpeG8g/KG
; xQAmpqutY7E/fcWMYYq5tglgShJF6xtOAQgM8b9ItrEYYBa480ZGqV49geh4bVHpyfqYigXO5QHWhU
; pnOLNdSL+pOGAKwE26pHO1yrAacwIlvIoZ5o2hc/CVLx7sWf3gmArX2EjmmiaALnZzN85G8jEA/Q2s
; WTmZWwWpV0JIGuvJU6fAx9HIQUlLl+JaeYB1AaoQAvjyrt8577i0FX1fHWvwyqJ/Hj7jP+8MhPPvT3
; 79KIDGkT0ck603+cBPY0EL6m/fbwKYkt3zBrMG0GfCE/5eZkcsSUQwMKQgt93syOupUrKpJin1S9eC
; A2GW2XI4eIrnkcZyHXPC6FIvOX8r15Pr7+po7TCJTjQHpXybvHHX1hzl0bP01nI+9IdxZ+bwDSbjgE
; ABGXWTSuhsjkYOGDp6dLtULAMHwqwnJzmV+hzbgLQEwjgo7mkG5sU89kNzNETyN3Fa6pKlwthE6p49
; yyWYu7Yjby5cEwiNjbHvXfed8nxdm1zDrkA0t5q6zTpuZsDRA8gFVMDMUOUxJSE1GTIHAWAG30Ri47
; FBzcBeG7G35N3J4pKkXl632rr2RNqR9907Tzou/7NX9bY83xR+QxeA1JjdcqilEmuDtBfAMQiBRlpY
; OckJoFkz3jYpNUW9iX62HhskMauDBDDqGIBJ5J26ftdOa5h2UF6xvvPdJ20t/eojYGYBpIJzKmcMUG
; rG/w8CwEEaHJOuCSK7vzVFRVhkDsAeCAWtOTxikVR+Eguo5JbdtknJK0pzjC1pqF0J55TX1vU7kRJe
; nzrmoByE9MNNMyE1RceYxTkhvXxgzhHWsdvYgaSS+9SHKHq2sAhV6efctswxCDWQjcfRyDpuqZLjoJ
; SHsG9SchpY7egMUu6Y+RLQpybJiXSA0nNXvWJ9x4Vv64avBjA5isMLq1sA5oAhs3gsFgggM3zqjYtj
; UlAF2Ep5zdfYqghpwlZzYkMOOOqFkJTm2Eid0paW5ImDAhyQzCWvtlRuDs0EYeuaTIRsCxirh3KiHa
; D05KWvWwSfvyfGnJN59wEIGmov5zf3rIbkiNesgMwBaDBcnyD03NowKJL4KGxSxwNbOYNyEwU9eVng
; 6nFSssw2Z7eV0lM7AtWUis0zwMpT9t2xumjDrWeeOAcoPXfVy7tUr7HUB/5fnku+KuMzVG7PmnC9Gq
; LjSChqppaGpepl5+X9uEuyY5LgQJVmPbkFH3Vn3ZGjYR3Xc3qdlEhD9WvZbbVazV6TJfdXxg5Qqtty
; /YWnrh86/Hc7A2FLJX/1rNX61n9cDWM0Bl+kHhZq+AYAXUDiCa9E6m2aFQOMvHK+BDCORjzbqZDM1P
; owx0EkXeBYSKgcuCSMkpQk0xIPuZZUwCrPlSltygA6d3zuHOjlAUqthFt9RRjskjQsHZTAN5RjfZLU
; qxJA46yfAmPrnTQr9lFSpluecC+AgTDLU9ljkDPiWqewbwKhAeJYZEce6IWIeLiCy61jejcpWU9OVq
; 92kHpTR78tLUkr81Ndc8ijiZYg/LAqtGMv5Ln7zQV8xwpGaIW83gMfyVaPCm7B5y1dKzO+Fp3bQggg
; s0L4RqUSwlkSnJ6CUBHyoGoli/7hD38YJOJBxAtrSaX+lh3nbLee0qpX1D4N5GcZhK/LrryQpwYw3G
; hPlh2NX+n5tuAbANTYgwbQQJF6KmLgdPImAI5BqM4ktyW8559/fjg2hDQcOxlqUxiTAgYMKpm0PQjo
; ypL9J4LX1kbrNfG67MILecYATM5k3ryAmynpNwDIzsmBQ9tCCD4qJEfC+t0gGERqZSzrdgmE7mPnnR
; UTXrH7G7y8rDnryUtKyw7M0XFRJbHbcpzcJrDVRb/rq6h5hf0696qtl/qNoTWAOMgr1yLxkiAcSdiC
; bwAwa7F0eFLzNwHQAORt2i1PWKe23oK5BEKgCa1YM65fX5+EVwcoJe63FIhSImWduAaVvZb3lGxy/9
; rRaAXhhY5MWs8vwavLSyUNawCz86212mHSamMgLOEbAEx2Qvkq9SUQeojBR7sOm1qeU1Edm+2AvRBS
; hcIqpJ713HJg6nCNExdIQ1IyR7z1QlHuNZm61uw2mfIG8aWAq1f2s4xJuqzSjJ1kn+Jt8i81gK2ltl
; LiGW+2NF6aAGZhWAcZhKRfzQGoAxCuQ8u14bk14vIVUXMQGmgrIdmPO+ecKBqbN0eSmnNQANp3El7p
; BRZEcU56vqNvSb14vVNt0E7P0Fetba11v72YKrkGcAq+lKR0aVMk4RlnnPHvAAbCOBGgMjBjEOaESw
; PWckamIFSSqDn2ulYVTXgFgPUm6jkI1V1qF3BJT2qgBUXWtZkISyRZKdFy8GX9t7IuYE14ZQ68up2R
; zHPHZ9xx9t+/5ABOORz+n35wbRPAqN7se9B4IAU+/zdY2QMy5xVPQWiQGN21g+L+YnrWcSW/jtlAPS
; BSY2KGOe+6tLXyEp1eCdYquZf+SIpX+Xzg5wiMKak3ZwN7hr7ynBZ8+szgXnHkpPX9p778JQFwCr6y
; 6AfSUL1XY6/pSkZ0HJSoKqozb8TsDc1MQagSOUaNdBCKoD7tGam3cC4N15QQ8JDdF9B+jxkwpwp7S6
; RpeUoDKJTy7MMl0NXqNlEAzwCkz+Jtel7Zrzcffv2LCmAvfKSe4ju0xmruPXGg0kgqIIeGZ624BeAm
; ECZ8AxBp8o7CMKBLvOQ5GN1PQFnwWm4gaXIQ4LVUv77KKyxqh2lJO8ZUbcZD8Jpd3MpGGnauHZOG9/
; 0VpGENYAu+FoCBryzHAVhDGKchb0GMujxICKlBIRSqEiQ5nneTcE0Lxqgwbcir7ZUk2h4UfO7lGeDO
; mnHrDJZNwSsBlPEDvrxcpgSvLjcfet2LCuCU5Etx3SAB/WcMwmT5GjxQxUHhySVXcBsI3Tf7hGW5ZH
; snFZnM4rFBWAJgUsCYEgHFTjzP5aiMvc5qqeRz/7ymNJ8BsfVCnqXQRcqpK/CigtO2+o1F9f6Ny896
; 24sCYA982is6QRs1AVThLIprQL1CkoyRhGvGAJyC0P3l+YntsftqqWgAOQ15PcAmIALNZDFA4L6gEe
; LJmyMBX6vIXpUZRyMg1/dovZCnF7qA5yeQsyenLO5FEuqrWgqWYwHCg1DJYwDOwed3zDCxLKOaqKt8
; uUyXzkbwsQzX0kHRuZGQPRDqSLl9VjPYYq0OLR0UFU7a0txAlYObRf4APAYPMB2ko0Ps2p/KVWwBnn
; OVW4DXz0mQewl4SpYB9XNt55VaxQRIKtrYWBi7m05/7YEDOAefOjJJTHjbLPz98OHD+wEEQ05EODLx
; /uDyFAUdO7j/L2zbm4Iwm5LF9qjeBK+nnJNyPTnLhXMQZiCW2F8ywdWLVO5RmWl33pnWo1pNBPdOOG
; gKuhQTPK/JmLLzUtTF/dWrBV/KZWe+dWNp2PKCp+AzDlaoaDvtB55y6NChvwCoUbFdWmt6UxAqifJn
; 6asFnzCL01NJPs9a6iUbHNKMVBtzUIBKeicpdqndWB6gxMhvgXXhC4Fh8NWA90q2hGti447FSLWjPP
; ZkCrxy8gdc9rv7txYTosXuOPL3WwNIaOGhhs9nxoOJIw6rbiV8A4CMV8tQKtNyRnoh1AHupeFsonRI
; EkhJF9LPAM515BSIWU/OC/PKQSXiWy/FXlLUzwoMB8WhlNlmoJS2b5yAbZ4DsGxxrVeJys97wauL+s
; b+reFLwHxwNs94y1YAxgY1aQKg/pGjKazG4Qh4JXwDgDmcvPRkNoUw0tA9SSv0s6/o/ZzA3+OgzIGo
; we5NkmYzeLz1baAoi3tbS3ZiQ07d9xkgl0i7KfXqM/czcRIvzN6aub6ZAq9Ut9FuxsPvntlKvzO+97
; 7zZRsBmGU2fUQAeZ5kEGE17RqDb08Ft8o2EOpIBj2dT6WlwUu85DkQdSTRT1olsaH++7YF0E5rkPCq
; Q7MFdRPY5mxcMcns+tsUutrOK9fuaSd2LtNhas/ujae9ZjGAUbnazXT5/e9/P2gPHE3BNwBYS79tIa
; Q+LP6L8VC9CU/MdV4PiIExkiObYUiNBMjnBnsJgO5Nsjrp0zZP0jyqcRPQxgoJm6TdHJl8EOCVUjDv
; TcnRaq0UqpRLD//zpDRsSUD3fPTRRweV6xkK1Q/MMfhOP/309SrriNtCqKF5nxgjPke2xmgfc1CWgu
; h+IMiifAZRByfhdVsgEmJi67EtfZb9ydpmtaaWuEtK6bECrgwiG4usoMz11Rx4xkU941yWQsK4e95U
; JssNI9KwBtC9mCsWE9wnEs9zaSmfteAbAPRHYtkAji0qzzknOs3rGBjufmpYPQOT4lU6KEtAdI9si0
; wyRF0yeDp4U+kURyNB5Vp62jutnfYfJxDfA1td3H8scBwbtNxl1gtdCVpik7W69dPnSacbG3flkkNv
; Pk4a1gDKWiLFS3Ubqae+CWv5LODtARgDMsmPGr9EGvoOQ52joUFjtmE84rwaSoV6ZngGxATJuuecij
; Zw2Zm1BD5gq1+k3lgxkfLmyOynnoKtLK4tM4rGVGyiCuUhoT3glftxS0ejNXa+oy0Jo0wtqZUQBsD7
; j7x6/exjDw0TtQVfit/1q0IlHwdgigrF05uDUAdJbWIbOU6NOulxUGJb9a4n63wiXuV77UQlYZnE0e
; bUujYnqNwjxcBtJx5PL6fpz9XJNeDTB0smn4ln0s6BF21UjsWY5irHM32sTVOrGhef/k97AD5x14VD
; xk9svDlnA2yR7Nrl99NOO229yhpdigoZPB3lwhaEBopBLrbHsyobOgZhLQ2T8JqluDrl32egSHxpE5
; sxaibea+sagGZnYK8UK4v7C67TAv4/dh0poz294JWARWWzcc9/IbBc923a4mcPeHVxTyaBvqghLNdx
; P/Xgjetn7vmLjdwDXmnvKe4V4TN4weVCcVk0JK8vTSU1jMpxdp/odnY79XrJNYit9eR8To0mGaJ30M
; aA1KlZIy1VoWcneXQpeLXtmXgnj5lETX08M5vze4EbK0nQICDK/kzmzRR4U/CVKfOktHFXp3IdV/9x
; wIRXso7bI/XqQuopxtuk/DfR1psTQJf0EgAAAABJRU5ErkJggg==
; thumbnail end
;
; 

; external perimeters extrusion width = 3.00mm
; perimeters extrusion width = 3.00mm
; infill extrusion width = 3.00mm
; solid infill extrusion width = 3.00mm
; top infill extrusion width = 3.00mm
; first layer extrusion width = 3.00mm

M73 P0 R6
M73 Q0 S6
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P2 ; nozzle diameter check
M115 U3.14.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 X123.5 Y55 W3 H100 ; mesh bed levelling

G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line
M73 P1 R5
M73 Q1 S5

G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.

G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion

M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0




M107
;LAYER_CHANGE
;Z:2
;HEIGHT:2
G1 E-.8 F2100
G1 Z2.4 F7800
G1 X125 Y153.5
G1 Z2
M73 P2 R5
M73 Q2 S5
G1 E.8 F2100
;TYPE:External perimeter
;WIDTH:3
G1 F175.043
G1 X125 Y56.5 E207.34968
M106 S84.15
;LAYER_CHANGE
;Z:4
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;4


;WIPE_START
G1 F6240
M73 P11 R5
M73 Q11 S5
G1 X125 Y59.002 E-.8
;WIPE_END
G1 Z4 F7800
;AFTER_LAYER_CHANGE
;4
M104 S210 ; set temperature
G1 Z4.4
G1 X125 Y153.5
G1 Z4
G1 E.8 F2100
G1 F175.043
G1 X125 Y56.5 E207.34968
M106 S170.85
;LAYER_CHANGE
;Z:6
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;6


;WIPE_START
G1 F6240
M73 P21 R4
M73 Q21 S4
G1 X125 Y59.002 E-.8
;WIPE_END
G1 Z6 F7800
;AFTER_LAYER_CHANGE
;6
G1 Z6.4
G1 X125 Y153.5
G1 Z6
G1 E.8 F2100
G1 F175.043
G1 X125 Y56.5 E207.34968
M106 S255
;LAYER_CHANGE
;Z:8
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;8


;WIPE_START
G1 F6240
M73 P30 R4
M73 Q30 S4
G1 X125 Y59.002 E-.8
;WIPE_END
G1 Z8 F7800
;AFTER_LAYER_CHANGE
;8
G1 Z8.4
G1 X125 Y153.5
G1 Z8
M73 P31 R4
M73 Q31 S4
G1 E.8 F2100
G1 F175.043
G1 X125 Y56.5 E207.34968
;LAYER_CHANGE
;Z:10
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;10


;WIPE_START
G1 F6240
M73 P40 R3
M73 Q40 S3
G1 X125 Y59.002 E-.8
;WIPE_END
G1 Z10 F7800
;AFTER_LAYER_CHANGE
;10
G1 Z10.4
G1 X125 Y153.5
G1 Z10
G1 E.8 F2100
G1 F175.043
G1 X125 Y56.5 E207.34968
;LAYER_CHANGE
;Z:12
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;12


;WIPE_START
G1 F6240
M73 P49 R3
M73 Q49 S3
G1 X125 Y59.002 E-.8
;WIPE_END
G1 Z12 F7800
;AFTER_LAYER_CHANGE
;12
G1 Z12.4
G1 X125 Y153.5
M73 Q50 S3
G1 Z12
M73 P50 R2
G1 E.8 F2100
G1 F175.043
G1 X125 Y56.5 E207.34968
;LAYER_CHANGE
;Z:14
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;14


;WIPE_START
G1 F6240
M73 P59 R2
M73 Q59 S2
G1 X125 Y59.002 E-.8
;WIPE_END
G1 Z14 F7800
;AFTER_LAYER_CHANGE
;14
G1 Z14.4
G1 X125 Y153.5
G1 Z14
G1 E.8 F2100
G1 F175.043
G1 X125 Y56.5 E207.34968
;LAYER_CHANGE
;Z:16
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;16


;WIPE_START
G1 F6240
M73 P69 R1
M73 Q69 S1
G1 X125 Y59.002 E-.8
;WIPE_END
G1 Z16 F7800
;AFTER_LAYER_CHANGE
;16
G1 Z16.4
G1 X125 Y153.5
G1 Z16
G1 E.8 F2100
G1 F175.043
G1 X125 Y56.5 E207.34968
;LAYER_CHANGE
;Z:18
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;18


;WIPE_START
G1 F6240
M73 P78 R1
M73 Q78 S1
G1 X125 Y59.002 E-.8
;WIPE_END
G1 Z18 F7800
;AFTER_LAYER_CHANGE
;18
G1 Z18.4
G1 X125 Y153.5
G1 Z18
M73 P79 R1
M73 Q79 S1
G1 E.8 F2100
G1 F175.043
G1 X125 Y56.5 E207.34968
;LAYER_CHANGE
;Z:20
;HEIGHT:2
;BEFORE_LAYER_CHANGE
G92 E0.0
;20


;WIPE_START
G1 F6240
M73 P88 R0
M73 Q88 S0
G1 X125 Y59.002 E-.8
;WIPE_END
G1 Z20 F7800
;AFTER_LAYER_CHANGE
;20
G1 Z20.4
G1 X125 Y153.5
G1 Z20
G1 E.8 F2100
G1 F175.043
G1 X125 Y56.5 E207.34968
;WIPE_START
G1 F6240;_WIPE
M73 P97 R0
M73 Q97 S0
G1 X125 Y59.002 E-.8
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z21 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
M73 Q98 S0
G1 Z69 F720 ; Move print head further up
M73 P98 R0
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M84 ; disable motors
; max_layer_z = 20
M73 P100 R0
M73 Q100 S0
; objects_info = {"objects":[]}
; filament used [mm] = 2095.00
; filament used [cm3] = 5.04
; filament used [g] = 6.25
; filament cost = 0.16
; total filament used [g] = 6.25
; total filament cost = 0.16
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 6m 0s
; estimated printing time (silent mode) = 6m 2s
; estimated first layer printing time (normal mode) = 41s
; estimated first layer printing time (silent mode) = 42s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; bed_temperature_extruder = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600\nG1 E0.3 F1500 ; prime after color change
; colorprint_heights = 
; compatible_printers_condition_cummulative = ;"nozzle_diameter[0]!=0.8 and printer_notes!~/.*PG.*/ and printer_notes!~/.*MINIIS.*/ and printer_model!=\"MK3.5\" and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_perimeter_transition_distance = 0
; cooling_slowdown_logic = uniform_cooling
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; custom_parameters_filament = ""
; custom_parameters_print = 
; custom_parameters_printer = 
; default_acceleration = 0
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 3
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 3
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_abrasive = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_length_toolchange = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = nil
; filament_settings_id = "Generic PLA"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = nil
; filament_travel_ramping_lift = nil
; filament_travel_slope = nil
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filament_wipe = nil
; fill_angle = 45
; fill_density = 20%
; fill_pattern = gyroid
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 3
; first_layer_height = 2
; first_layer_infill_speed = 0
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil
; infill_acceleration = 0
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 3
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = ;;"Original Prusa i3 MK3S & MK3S+"
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 2
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 3
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = WAAM Multi-Layer Slicing Settings
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = WAAM Settings
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 12
; small_perimeter_speed = 15
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 3
; solid_infill_speed = 20
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "{if printer_notes!~/.*(MK3.5|MINIIS).*/}\nM900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0\n{endif}\n\n{if printer_notes=~/.*MINIIS.*/}\nM572 S{if nozzle_diameter[0]==0.6}0.17{elsif nozzle_diameter[0]==0.8}0.12{elsif nozzle_diameter[0]==0.4}0.27{elsif nozzle_diameter[0]==0.25}0.85{else}0{endif}\n{endif}\n\n{if printer_notes=~/.*MK3.5.*/}\nM572 S{if nozzle_diameter[0]==0.4}0.035{elsif nozzle_diameter[0]==0.5}0.025{elsif nozzle_diameter[0]==0.6}0.02{elsif nozzle_diameter[0]==0.8}0.014{elsif nozzle_diameter[0]==0.25}0.12{elsif nozzle_diameter[0]==0.3}0.08{else}0{endif} ; Filament gcode\n{endif}"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.14.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 X{first_layer_print_min[0]} Y{first_layer_print_min[1]} W{(first_layer_print_max[0]) - (first_layer_print_min[0])} H{(first_layer_print_max[1]) - (first_layer_print_min[1])} ; mesh bed levelling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 3
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 15
; top_solid_layers = 6
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_short_distance_acceleration = 0
; travel_slope = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
M84 ; disable motors
