controller_manager:
  ros__parameters:
    update_rate: 250  # frequency in Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    welding_io_controller:
      type: gpio_controllers/GpioCommandController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      
    state_publish_rate: 250.0
    action_monitor_rate: 20.0
    
    # Slower for WAAM
    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true

welding_io_controller:
  ros__parameters:
    gpios:
      - welding_arc
      - wire_feed
      - gas_flow
    command_interfaces:
      welding_arc: [digital_output]
      wire_feed: [digital_output]
      gas_flow: [digital_output]
    state_interfaces:
      welding_enable: [digital_input]
      user_confirm: [digital_input]
      system_fault: [digital_input]